apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      component: static
  template:
    metadata:
      labels:
        component: static
    spec:
      containers:
        - name: nginx
          image: xuxant/nginx
          ports:
            - containerPort: 80