apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      component: servlet
  template:
    metadata:
      labels:
        component: servlet
    spec:
      containers:
        - name: tomcat
          image: xuxant/tomcat
          ports:
            - containerPort: 8080